title: blog.chyidl.com
description: "record life and share knowledge"
author:
  name: "chyi"
  email: "chyiyaqing@gmail.com"
  url: "https://blog.chyidl.com/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "ChyiYaqing"
year : "2020"
